name: Release

on:
  push:
    # branches:
    #   - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          # pulls all commits (needed for lerna / semantic release to correctly version)
          fetch-depth: '0'
        # pulls all tags (needed for lerna / semantic release to correctly version)
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Configure CI Git User
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://$ACTOR:$ACTOR_PAT@github.com/scalar-css/scalar-css
        env:
          ACTOR: ${{ secrets.ACTOR }}
          ACTOR_PAT: ${{ secrets.ACTOR_PAT }}
      - name: Checkout and pull branch
        run: git checkout "${GITHUB_REF:11}" && git pull
      - name: Install Packages
        run: yarn install
      - name: Test
        run: yarn test
      # - name: Authenticate with Registry
      #   run: |
      #     yarn logout
      #     echo "@scalar-css:registry=http://npm.pkg.github.com/" > .npmrc
      #     echo "registry=http://npm.pkg.github.com/" >> .npmrc
      #     echo "//npm.pkg.github.com/:_authToken=$NPM_TOKEN" >> .npmrc
      #     npm whoami
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.ACTOR_PAT }}
      # - name: Publish package
      #   run: npm run deploy:ci
      #   env:
      #     GH_TOKEN: ${{ secrets.ACTOR_PAT }}
      #     GITHUB_TOKEN: ${{ secrets.ACTOR_PAT }}
      # - name: Build Docs
      #   run: yarn docs
      # - run: echo "apolloelements.dev" > docs/CNAME
      # - name: Deploy Docs
      #   uses: JamesIves/github-pages-deploy-action@releases/v3
      #   with:
      #     ACCESS_TOKEN: ${{ secrets.ACTOR_PAT }}
      #     BRANCH: gh-pages # The branch the action should deploy to.
      #     FOLDER: docs # The folder the action should deploy.
